basePath: /
definitions:
  auth.AuthData:
    properties:
      pass:
        type: string
      userId:
        type: string
    type: object
info:
  contact:
    name: Junio Cesar Ferreira
  license:
    name: MIT
  title: JWT Login API
  version: 1.0.0
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Verifica se usuário é registrado e realiza login
      parameters:
      - description: Usuário e Hash
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/auth.AuthData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Tenta validar usuário e fazer login
      tags:
      - Login
  /protected:
    get:
      description: Testando Token
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Rota protegida com autenticação utilizando Token
      tags:
      - Login
  /renew:
    get:
      description: Renova o token de autenticação se o token atual for válido e está
        prestes a expirar
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Token renovado com sucesso
          schema:
            type: string
      summary: Renova o token de autenticação
      tags:
      - Login
swagger: "2.0"
