services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - PORT=8082